[package]
authors = ["Jason Knight <Jason@JasonKnight.us>"]
name = "pi-gpio"
version = "0.1.0"
[dependencies]
env_logger = "0.5.6"
log = "0.4.1"
rand = "0.4.2"
rppal = "0.4.0"
simple-server = "0.3.0"
reqwest = "0.8.5"
